"""
M5 Schemas
===========
All Pydantic schemas used across Architecture 2.
Import from here — never define schemas inline in other files.
"""

from typing import Literal

from pydantic import BaseModel, Field, field_validator


# -- Schema 1: PlannerOutput --------------------------------------------------

class PlannerOutput(BaseModel):
    """Structured output from the intent-classification LLM call."""

    intent: Literal[
        "data_query",
        "conversational",
        "multistep",
        "cannot_answer",
    ] = Field(
        description=(
            "Classification of the user's intent. "
            "data_query: wants data from the database. "
            "conversational: wants explanation or analysis "
            "of a prior result. Includes: why, explain, "
            "what does that mean, tell me more, is that "
            "good, how does that compare. "
            "multistep: wants two or more distinct queries "
            "in one question. Includes: first X then Y, "
            "compare A with B, show X and also Y. "
            "cannot_answer: outside scope of grocery "
            "purchasing data."
        )
    )
    reason: str = Field(
        description=(
            "One sentence explaining the classification. "
            "Be specific about which words or phrases "
            "in the question led to this intent."
        )
    )
    subqueries: list[str] = Field(
        default_factory=list,
        description=(
            "Populated only for multistep intent. "
            "Each item is a self-contained plain English "
            "sub-question that can be answered independently. "
            "Empty list for all other intents."
        ),
    )

    @field_validator("subqueries")
    @classmethod
    def subqueries_only_for_multistep(cls, v: list[str], info) -> list[str]:
        """Ensures subqueries is empty for non-multistep intents."""
        intent = info.data.get("intent")
        if intent and intent != "multistep" and len(v) > 0:
            return []
        return v


# -- Schema 2: CriticOutput ---------------------------------------------------

class CriticOutput(BaseModel):
    """Structured insight generated by the Critic agent."""

    answer: str = Field(
        description=(
            "One sentence directly answering the user's "
            "question using actual values from the result. "
            "Never be vague — always include specific numbers."
        )
    )
    finding: str = Field(
        description=(
            "The single most interesting or surprising "
            "thing in the data. Must include a specific "
            "number or comparison from the result."
        )
    )
    caveat: str = Field(
        description=(
            "One data quality note or limitation the user "
            "should know. Write exactly 'None.' if there "
            "are no caveats."
        )
    )
    followup: str = Field(
        description=(
            "One specific follow-up question the user "
            "might want to ask next. Must end with a "
            "question mark."
        )
    )

    @field_validator("followup")
    @classmethod
    def followup_must_be_question(cls, v: str) -> str:
        """Ensures followup ends with a question mark."""
        v = v.strip()
        if not v.endswith("?"):
            v = v + "?"
        return v

    @field_validator("answer", "finding", "caveat", "followup")
    @classmethod
    def no_empty_fields(cls, v: str) -> str:
        """Ensures no field is empty or whitespace only."""
        if not v.strip():
            raise ValueError("Field cannot be empty.")
        return v.strip()


# -- Schema 3: BenchmarkQuestionResult ----------------------------------------

class BenchmarkQuestionResult(BaseModel):
    """Immutable result record for a single benchmark question."""

    id:              str
    category:        str
    question:        str
    sql:             str
    sql_correct:     bool
    db_executed:     bool
    result_sane:     bool
    overall:         Literal[
                         "PASS", "PARTIAL", "FAIL",
                         "BLOCKED_OK", "BLOCKED_FAIL",
                     ]
    failed_checks:   list[str] = Field(default_factory=list)
    sanity_failures: list[str] = Field(default_factory=list)
    latency_ms:      int       = Field(ge=0, default=0)
    error:           str       = ""

    model_config = {"frozen": True}


# -- Schema 4: BenchmarkReport ------------------------------------------------

class BenchmarkReport(BaseModel):
    """Full benchmark run result with aggregated scores and per-question details."""

    architecture:     int
    timestamp:        str
    model:            str
    total:            int            = Field(ge=0)
    sql_correct:      int            = Field(ge=0)
    db_executed:      int            = Field(ge=0)
    result_sane:      int            = Field(ge=0)
    full_pass:        int            = Field(ge=0)
    blocked_ok:       int            = Field(ge=0)
    sql_pct:          float          = Field(ge=0, le=100)
    db_pct:           float          = Field(ge=0, le=100)
    sanity_pct:       float          = Field(ge=0, le=100)
    pass_pct:         float          = Field(ge=0, le=100)
    total_latency_ms: int            = Field(ge=0)
    avg_latency_ms:   int            = Field(ge=0)
    by_category:      dict[str, dict]
    questions:        list[BenchmarkQuestionResult]

    def to_json(self) -> str:
        """Serialises report to formatted JSON string."""
        return self.model_dump_json(indent=2)

    @classmethod
    def from_json(cls, json_str: str) -> "BenchmarkReport":
        """Deserialises report from JSON string."""
        return cls.model_validate_json(json_str)


# -- Self-test ----------------------------------------------------------------
if __name__ == "__main__":
    from pydantic import ValidationError

    # PlannerOutput valid
    p = PlannerOutput(intent="data_query", reason="User wants data", subqueries=[])
    assert p.intent == "data_query"
    assert p.subqueries == []

    # PlannerOutput invalid intent
    try:
        PlannerOutput(intent="invalid", reason="r", subqueries=[])  # type: ignore
        assert False, "Should have raised"
    except ValidationError:
        pass

    # Subqueries cleared for non-multistep
    p2 = PlannerOutput(intent="data_query", reason="r", subqueries=["q1", "q2"])
    assert p2.subqueries == []

    # Subqueries kept for multistep
    p3 = PlannerOutput(intent="multistep", reason="r", subqueries=["q1", "q2"])
    assert p3.subqueries == ["q1", "q2"]

    # CriticOutput followup gets ? appended
    c = CriticOutput(
        answer="Produce leads at 66.2%.",
        finding="Gap to dairy is 0.4%.",
        caveat="None.",
        followup="Which produce products drive this",
    )
    assert c.followup.endswith("?")

    # CriticOutput empty field rejected
    try:
        CriticOutput(answer="", finding="f", caveat="c", followup="q?")
        assert False, "Should have raised"
    except ValidationError:
        pass

    # BenchmarkQuestionResult immutable
    r = BenchmarkQuestionResult(
        id="ST01", category="single_table", question="q", sql="SELECT 1",
        sql_correct=True, db_executed=True, result_sane=True,
        overall="PASS", latency_ms=1000,
    )
    try:
        r.sql_correct = False  # type: ignore
        assert False, "Should have raised"
    except Exception:
        pass

    # BenchmarkReport round-trip
    report = BenchmarkReport(
        architecture=1, timestamp="2026-01-01T00:00:00",
        model="claude-sonnet-4-6", total=30,
        sql_correct=28, db_executed=27, result_sane=25,
        full_pass=24, blocked_ok=2,
        sql_pct=93.3, db_pct=90.0, sanity_pct=83.3,
        pass_pct=80.0, total_latency_ms=55000,
        avg_latency_ms=1833, by_category={}, questions=[],
    )
    json_str = report.to_json()
    restored = BenchmarkReport.from_json(json_str)
    assert restored.architecture == 1
    assert restored.pass_pct == 80.0

    print("m5_schemas self-test OK")
